use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

use crate::bindgen_prelude::{TypeDefKind, TYPE_DEF_DESCRIPTORS};

pub const DEFAULT_TYPE_DEF_HEADER: &str = "/* auto-generated by NAPI-RS */\n/* eslint-disable */\n";

const TOP_LEVEL_NAMESPACE: &str = "__TOP_LEVEL_MODULE__";

#[derive(Debug, Clone)]
pub struct IteratorInfo {
  pub yield_type: String,
  pub return_type: String,
  pub next_type: String,
}

#[derive(Debug, Clone)]
pub struct TypeDefLine {
  pub kind: TypeDefKind,
  pub name: String,
  pub original_name: Option<String>,
  pub def: String,
  pub extends: Option<String>,
  pub extends_kind: Option<TypeDefKind>,
  pub native_parent: Option<String>,
  pub js_doc: Option<String>,
  pub js_mod: Option<String>,
  pub iterator_info: Option<IteratorInfo>,
}

pub struct TypeDefOutput {
  pub dts: String,
  pub exports: Vec<String>,
}

pub fn collect_type_defs() -> Vec<TypeDefLine> {
  TYPE_DEF_DESCRIPTORS
    .iter()
    .map(|desc| {
      let iterator_info = desc.iterator_info.map(|info| IteratorInfo {
        yield_type: (info.yield_type)(),
        return_type: (info.return_type)(),
        next_type: (info.next_type)(),
      });
      TypeDefLine {
        kind: desc.kind,
        name: desc.name.to_owned(),
        original_name: desc.original_name.map(|s| s.to_owned()),
        def: (desc.def_fn)(),
        extends: None,
        extends_kind: None,
        native_parent: desc.native_parent_name.map(|s| s.to_owned()),
        js_doc: desc.js_doc.map(|s| s.to_owned()),
        js_mod: desc.js_mod.map(|s| s.trim_end_matches('\0').to_owned()),
        iterator_info,
      }
    })
    .collect()
}

pub struct GenerateDtsOptions<'a> {
  pub const_enum: bool,
  pub runtime_string_enum: bool,
  pub header: Option<&'a str>,
}

impl Default for GenerateDtsOptions<'_> {
  fn default() -> Self {
    Self {
      const_enum: false,
      runtime_string_enum: false,
      header: None,
    }
  }
}

pub fn generate_dts(
  output: &Path,
  const_enum: bool,
  runtime_string_enum: bool,
) -> std::io::Result<TypeDefOutput> {
  generate_dts_with_options(
    output,
    GenerateDtsOptions {
      const_enum,
      runtime_string_enum,
      ..Default::default()
    },
  )
}

pub fn generate_dts_with_options(
  output: &Path,
  options: GenerateDtsOptions<'_>,
) -> std::io::Result<TypeDefOutput> {
  let mut defs = collect_type_defs();
  let result = process_type_defs(&mut defs, options.const_enum, options.runtime_string_enum);

  let mut header = options
    .header
    .map(str::to_owned)
    .unwrap_or_else(|| DEFAULT_TYPE_DEF_HEADER.to_owned());

  if result.dts.contains("ReadableStream") && !header.contains("ReadableStream") {
    header.push_str("\nimport type { ReadableStream } from 'node:stream/web'\n");
  }

  if result.dts.contains("ExternalObject<") {
    header.push_str(
      "\nexport declare class ExternalObject<T> {\n\
       \x20 readonly '': {\n\
       \x20   readonly '': unique symbol\n\
       \x20   [K: symbol]: T\n\
       \x20 }\n\
       }\n",
    );
  }

  if result.dts.contains("TypedArray") {
    header.push_str(
      "\nexport type TypedArray = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array\n",
    );
  }

  let full_dts = format!("{header}\n{}", result.dts);
  std::fs::write(output, &full_dts)?;
  Ok(result)
}

pub fn process_type_defs(
  defs: &mut Vec<TypeDefLine>,
  const_enum: bool,
  runtime_string_enum: bool,
) -> TypeDefOutput {
  let grouped = preprocess_type_def(defs);

  let mut exports = Vec::new();
  let mut dts = String::new();
  let mut first = true;

  let mut sorted_namespaces: Vec<_> = grouped.into_iter().collect();
  sorted_namespaces.sort_by(|(a, _), (b, _)| a.cmp(b));

  for (namespace, ns_defs) in sorted_namespaces {
    if !first {
      dts.push_str("\n\n");
    }
    first = false;

    if namespace == TOP_LEVEL_NAMESPACE {
      let mut ns_first = true;
      let mut sorted_defs = ns_defs.clone();
      sorted_defs.sort_by(|a, b| {
        let a_is_class = matches!(
          a.kind,
          TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
        );
        let b_is_class = matches!(
          b.kind,
          TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
        );
        match (a_is_class, b_is_class) {
          (true, true) | (false, false) => a.name.cmp(&b.name),
          (true, false) => std::cmp::Ordering::Less,
          (false, true) => std::cmp::Ordering::Greater,
        }
      });
      for def in &sorted_defs {
        if !ns_first {
          dts.push_str("\n\n");
        }
        ns_first = false;

        match def.kind {
          TypeDefKind::Const
          | TypeDefKind::Enum
          | TypeDefKind::StringEnum
          | TypeDefKind::Fn
          | TypeDefKind::Struct
          | TypeDefKind::NonConstructibleClass => {
            exports.push(def.name.clone());
          }
          _ => {}
        }
        dts.push_str(&pretty_print(
          def,
          const_enum,
          runtime_string_enum,
          0,
          false,
        ));
      }
    } else {
      exports.push(namespace.clone());
      write!(dts, "export declare namespace {namespace} {{\n").unwrap();
      for def in &ns_defs {
        dts.push_str(&pretty_print(def, const_enum, runtime_string_enum, 2, true));
        dts.push('\n');
      }
      dts.push('}');
    }
  }
  dts.push('\n');

  TypeDefOutput { dts, exports }
}

fn pretty_print(
  line: &TypeDefLine,
  const_enum: bool,
  runtime_string_enum: bool,
  indent: usize,
  ambient: bool,
) -> String {
  let mut s = line.js_doc.clone().unwrap_or_default();

  match line.kind {
    TypeDefKind::Interface => {
      write!(s, "export interface {} {{\n{}\n}}", line.name, line.def).unwrap();
    }
    TypeDefKind::Type => {
      write!(s, "export type {} = \n{}", line.name, line.def).unwrap();
    }
    TypeDefKind::Enum => {
      let kw = if const_enum { "const enum" } else { "enum" };
      write!(
        s,
        "{} {kw} {} {{\n{}\n}}",
        export_declare(ambient),
        line.name,
        line.def
      )
      .unwrap();
    }
    TypeDefKind::StringEnum => {
      if const_enum {
        write!(
          s,
          "{} const enum {} {{\n{}\n}}",
          export_declare(ambient),
          line.name,
          line.def
        )
        .unwrap();
      } else if runtime_string_enum {
        write!(
          s,
          "{} enum {} {{\n{}\n}}",
          export_declare(ambient),
          line.name,
          line.def
        )
        .unwrap();
      } else {
        let union_parts: String = line
          .def
          .lines()
          .map(|l| {
            l.find('=')
              .map(|i| l[i + 1..].trim_end_matches(',').trim())
              .unwrap_or(l.trim())
          })
          .collect::<Vec<_>>()
          .join(" | ");
        write!(s, "export type {} = {union_parts};", line.name).unwrap();
      }
    }
    TypeDefKind::Struct => {
      let def = line.def.clone();
      let mut extends_clause = String::new();
      let mut instance_extends = String::new();

      if let Some(ref ext) = line.extends {
        match line.extends_kind {
          Some(TypeDefKind::Struct) | None => {
            write!(extends_clause, " extends {ext}").unwrap();
          }
          Some(TypeDefKind::NonConstructibleClass) => {
            write!(
              instance_extends,
              "{} interface {} extends {ext} {{}}",
              export_declare(ambient),
              line.name,
            )
            .unwrap();
          }
          _ => {}
        }
      }

      write!(
        s,
        "{} class {}{extends_clause} {{\n{def}\n}}",
        export_declare(ambient),
        line.name,
      )
      .unwrap();
      if !instance_extends.is_empty() {
        write!(s, "\n{instance_extends}").unwrap();
      }
      if let Some(ref orig) = line.original_name {
        if orig != &line.name {
          write!(s, "\nexport type {orig} = {}", line.name).unwrap();
        }
      }
    }
    TypeDefKind::NonConstructibleClass => {
      let (instance_def, static_def) = split_non_constructible_class_def(&line.def);
      let extends_clause = line
        .extends
        .as_ref()
        .map(|e| format!(" extends {e}"))
        .unwrap_or_default();

      write!(
        s,
        "export interface {}{extends_clause} {{\n{instance_def}\n}}",
        line.name,
      )
      .unwrap();
      write!(
        s,
        "\n{} const {}: {{\n{static_def}",
        export_declare(ambient),
        line.name,
      )
      .unwrap();
      if !static_def.is_empty() {
        s.push('\n');
      }
      s.push_str("[Symbol.hasInstance](value: unknown): boolean\n}");

      if let Some(ref orig) = line.original_name {
        if orig != &line.name {
          write!(s, "\nexport type {orig} = {}", line.name).unwrap();
        }
      }
    }
    TypeDefKind::Fn => {
      write!(s, "{} {}", export_declare(ambient), line.def).unwrap();
    }
    _ => {
      s.push_str(&line.def);
    }
  }

  correct_string_indent(&s, indent)
}

fn split_non_constructible_class_def(def: &str) -> (String, String) {
  let mut instance_lines = Vec::new();
  let mut static_lines = Vec::new();

  for line in def.lines() {
    let trimmed = line.trim();
    if trimmed.starts_with("constructor(") {
      continue;
    }
    if let Some(rest) = trimmed.strip_prefix("static ") {
      static_lines.push(rest.to_string());
    } else {
      instance_lines.push(line.to_string());
    }
  }

  (instance_lines.join("\n"), static_lines.join("\n"))
}

fn export_declare(ambient: bool) -> &'static str {
  if ambient {
    "export"
  } else {
    "export declare"
  }
}

pub fn correct_string_indent(src: &str, indent: usize) -> String {
  let mut bracket_depth: usize = 0;
  let mut result = Vec::new();

  for line in src.split('\n') {
    let trimmed = line.trim();
    if trimmed.is_empty() {
      result.push(String::new());
      continue;
    }

    let is_multiline_comment = trimmed.starts_with('*');
    let is_closing_bracket = trimmed.ends_with('}');
    let is_opening_bracket = trimmed.ends_with('{');
    let is_type_declaration = trimmed.ends_with('=');
    let is_type_variant = trimmed.starts_with('|');

    let right_indent;
    if (is_opening_bracket || is_type_declaration) && !is_multiline_comment {
      bracket_depth += 1;
      right_indent = indent + (bracket_depth - 1) * 2;
    } else {
      if is_closing_bracket && bracket_depth > 0 && !is_multiline_comment && !is_type_variant {
        bracket_depth -= 1;
      }
      right_indent = indent + bracket_depth * 2;
    }

    let extra = if is_multiline_comment { 1 } else { 0 };
    let total_indent = right_indent + extra;
    result.push(format!("{}{trimmed}", " ".repeat(total_indent)));
  }

  result.join("\n")
}

type NamespaceGroups = BTreeMap<String, Vec<TypeDefLine>>;

fn preprocess_type_def(defs: &mut [TypeDefLine]) -> NamespaceGroups {
  let mut namespace_grouped: BTreeMap<String, Vec<TypeDefLine>> = BTreeMap::new();
  let mut class_defs: BTreeMap<String, Vec<usize>> = BTreeMap::new();

  let namespace_of = |def: &TypeDefLine| -> String {
    def
      .js_mod
      .clone()
      .unwrap_or_else(|| TOP_LEVEL_NAMESPACE.to_string())
  };

  let class_key = |ns: &str, name: &str| -> String { format!("{ns}\0{name}") };

  for (i, def) in defs.iter().enumerate() {
    if matches!(
      def.kind,
      TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
    ) {
      let ns = namespace_of(def);
      class_defs
        .entry(class_key(&ns, &def.name))
        .or_default()
        .push(i);
      if let Some(ref orig) = def.original_name {
        if orig != &def.name {
          class_defs.entry(class_key(&ns, orig)).or_default().push(i);
        }
      }
    }
  }

  let find_class = |ns: &str, name: &str| -> Option<usize> {
    let key = class_key(ns, name);
    match class_defs.get(&key) {
      None => None,
      Some(indices) if indices.len() == 1 => Some(indices[0]),
      Some(_) => None,
    }
  };

  let len = defs.len();
  let mut skip = vec![false; len];

  for i in 0..len {
    let ns = namespace_of(&defs[i]);

    match defs[i].kind {
      TypeDefKind::Struct | TypeDefKind::NonConstructibleClass => {
        if defs[i].native_parent.is_some() {
          let parent_name = defs[i].native_parent.clone().unwrap();
          if let Some(pidx) = find_class(&ns, &parent_name) {
            let parent_name = defs[pidx].name.clone();
            let parent_kind = defs[pidx].kind;
            defs[i].extends = Some(parent_name);
            defs[i].extends_kind = Some(parent_kind);
          }
        }
      }
      TypeDefKind::IteratorExtends => {
        skip[i] = true;
        let def_name = defs[i].name.clone();
        if let Some(cidx) = find_class(&ns, &def_name) {
          if let Some(ref info) = defs[i].iterator_info {
            let extends_str = format!(
              "Iterator<{}, {}, {}>",
              info.yield_type, info.return_type, info.next_type
            );
            let next_sig = format!(
              "next(value?: {}): IteratorResult<{}, {}>",
              info.next_type, info.yield_type, info.return_type
            );
            defs[cidx].extends = Some(extends_str);
            if !defs[cidx].def.is_empty() {
              defs[cidx].def.push('\n');
            }
            defs[cidx].def.push_str(&next_sig);
          }
        }
      }
      TypeDefKind::Impl => {
        skip[i] = true;
        let def_name = defs[i].name.clone();
        let def_def = defs[i].def.clone();
        if let Some(cidx) = find_class(&ns, &def_name) {
          if !defs[cidx].def.is_empty() {
            defs[cidx].def.push('\n');
          }
          defs[cidx].def.push_str(&def_def);
          if defs[cidx].kind == TypeDefKind::NonConstructibleClass
            && has_constructor_signature(&def_def)
          {
            defs[cidx].kind = TypeDefKind::Struct;
          }
        }
      }
      _ => {}
    }
  }

  for indices in class_defs.values() {
    for &idx in indices {
      if defs[idx].kind == TypeDefKind::Struct && !has_constructor_signature(&defs[idx].def) {
        defs[idx].kind = TypeDefKind::NonConstructibleClass;
      }
    }
  }

  for i in 0..len {
    if skip[i] {
      continue;
    }
    if matches!(
      defs[i].kind,
      TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
    ) {
      defs[i].def = sort_class_members(&defs[i].def);
    }
  }

  for (i, def) in defs.iter().enumerate() {
    if skip[i] {
      continue;
    }
    let ns = namespace_of(def);
    namespace_grouped.entry(ns).or_default().push(def.clone());
  }

  namespace_grouped
}

fn has_constructor_signature(def: &str) -> bool {
  def
    .lines()
    .any(|l| l.trim().starts_with("constructor(") || l.trim().starts_with("constructor ("))
}

fn sort_class_members(def: &str) -> String {
  let blocks = split_member_blocks(def);
  let mut sorted = blocks;
  sorted.sort_by(|a, b| member_sort_key(a).cmp(&member_sort_key(b)));
  sorted.join("\n")
}

fn is_jsdoc_line(trimmed: &str) -> bool {
  trimmed.starts_with("/**") || trimmed.starts_with("* ") || trimmed == "*/" || trimmed == "*"
}

fn split_member_blocks(def: &str) -> Vec<String> {
  let mut blocks = Vec::new();
  let mut pending_jsdoc: Vec<String> = Vec::new();

  for line in def.lines() {
    let trimmed = line.trim();
    if trimmed.is_empty() {
      continue;
    }

    if is_jsdoc_line(trimmed) {
      pending_jsdoc.push(line.to_owned());
    } else {
      if !pending_jsdoc.is_empty() {
        pending_jsdoc.push(line.to_owned());
        blocks.push(pending_jsdoc.join("\n"));
        pending_jsdoc = Vec::new();
      } else {
        blocks.push(line.to_owned());
      }
    }
  }

  blocks
}

fn member_sort_key(block: &str) -> (u8, String) {
  let sig_line = block
    .lines()
    .map(|l| l.trim())
    .find(|l| {
      !l.is_empty() && !l.starts_with("/**") && !l.starts_with("* ") && *l != "*/" && *l != "*"
    })
    .unwrap_or("");

  let category = if sig_line.starts_with("constructor(") || sig_line.starts_with("constructor (") {
    0
  } else if sig_line.starts_with("readonly ")
    || sig_line.starts_with("optional ")
    || (!sig_line.starts_with("get ")
      && !sig_line.starts_with("set ")
      && !sig_line.starts_with("static ")
      && !sig_line.contains('('))
  {
    1 // field
  } else if sig_line.starts_with("get ") {
    2
  } else if sig_line.starts_with("set ") {
    3
  } else if sig_line.starts_with("static ") {
    5
  } else {
    4 // instance method
  };

  let name = extract_member_name(sig_line);
  (category, name)
}

fn extract_member_name(sig: &str) -> String {
  let s = sig
    .strip_prefix("static ")
    .or_else(|| sig.strip_prefix("get "))
    .or_else(|| sig.strip_prefix("set "))
    .or_else(|| sig.strip_prefix("readonly "))
    .unwrap_or(sig);

  s.split(&['(', ':', '<', '?'][..])
    .next()
    .unwrap_or("")
    .trim()
    .to_owned()
}
