use std::fmt::Write;

const BINDING_HEADER: &str = r#"// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */
"#;

const MUSL_DETECTION: &str = include_str!("templates/musl-detection.js");
const WIRE_PROTOTYPES: &str = include_str!("templates/wire-prototypes.js");
const LOAD_ERROR_HANDLER: &str = include_str!("templates/load-error.js");

pub fn create_cjs_binding(
  local_name: &str,
  pkg_name: &str,
  idents: &[String],
  package_version: Option<&str>,
) -> String {
  let mut out = String::with_capacity(4096);
  out.push_str(BINDING_HEADER);
  out.push('\n');
  out.push_str(&create_common_binding(
    local_name,
    pkg_name,
    package_version,
  ));
  out.push_str("module.exports = nativeBinding\n");
  for ident in idents {
    writeln!(out, "module.exports.{ident} = nativeBinding.{ident}").unwrap();
  }
  out
}

pub fn create_esm_binding(
  local_name: &str,
  pkg_name: &str,
  idents: &[String],
  package_version: Option<&str>,
) -> String {
  let mut out = String::with_capacity(4096);
  out.push_str(BINDING_HEADER);
  out.push_str(
    "\nimport { createRequire } from 'node:module'\n\
         const require = createRequire(import.meta.url)\n\
         const __dirname = new URL('.', import.meta.url).pathname\n\n",
  );
  out.push_str(&create_common_binding(
    local_name,
    pkg_name,
    package_version,
  ));
  write!(out, "const {{ {} }} = nativeBinding\n", idents.join(", ")).unwrap();
  for ident in idents {
    writeln!(out, "export {{ {ident} }}").unwrap();
  }
  out
}

fn create_common_binding(
  local_name: &str,
  pkg_name: &str,
  package_version: Option<&str>,
) -> String {
  let mut s = String::with_capacity(8192);

  s.push_str(MUSL_DETECTION);
  s.push_str("\nfunction requireNative() {\n");
  s.push_str("  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {\n");
  s.push_str("    try {\n");
  s.push_str("      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);\n");
  s.push_str("    } catch (err) {\n");
  s.push_str("      loadErrors.push(err)\n");
  s.push_str("    }\n");

  write_platform_block(&mut s, local_name, pkg_name, package_version);

  s.push_str("}\n\n");
  s.push_str(WIRE_PROTOTYPES);
  s.push_str(
    "\nnativeBinding = requireNative()\n\n\
         if (!nativeBinding) {\n",
  );
  s.push_str(LOAD_ERROR_HANDLER);
  s.push_str("}\n\n");
  s.push_str("wireNativeClassPrototypes(nativeBinding)\n");
  s.push_str("hideNativeClassMetadata(nativeBinding)\n");
  s
}

fn require_tuple(
  out: &mut String,
  local_name: &str,
  pkg_name: &str,
  tuple: &str,
  indent: usize,
  package_version: Option<&str>,
) {
  let pad = " ".repeat(indent);
  let inner = " ".repeat(indent + 2);

  writeln!(out, "{pad}try {{").unwrap();
  writeln!(out, "{inner}return require('./{local_name}.{tuple}.node')").unwrap();
  writeln!(out, "{pad}}} catch (e) {{").unwrap();
  writeln!(out, "{inner}loadErrors.push(e)").unwrap();
  writeln!(out, "{pad}}}").unwrap();

  if let Some(ver) = package_version {
    writeln!(out, "{pad}try {{").unwrap();
    writeln!(out, "{inner}const binding = require('{pkg_name}-{tuple}')").unwrap();
    writeln!(
      out,
      "{inner}const bindingPackageVersion = require('{pkg_name}-{tuple}/package.json').version"
    )
    .unwrap();
    writeln!(out, "{inner}if (bindingPackageVersion !== '{ver}' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {{").unwrap();
    writeln!(out, "{inner}  throw new Error(`Native binding package version mismatch, expected {ver} but got ${{bindingPackageVersion}}. You can reinstall dependencies to fix this issue.`)").unwrap();
    writeln!(out, "{inner}}}").unwrap();
    writeln!(out, "{inner}return binding").unwrap();
    writeln!(out, "{pad}}} catch (e) {{").unwrap();
    writeln!(out, "{inner}loadErrors.push(e)").unwrap();
    writeln!(out, "{pad}}}").unwrap();
  } else {
    writeln!(out, "{pad}try {{").unwrap();
    writeln!(out, "{inner}return require('{pkg_name}-{tuple}')").unwrap();
    writeln!(out, "{pad}}} catch (e) {{").unwrap();
    writeln!(out, "{inner}loadErrors.push(e)").unwrap();
    writeln!(out, "{pad}}}").unwrap();
  }
}

fn write_platform_block(s: &mut String, local_name: &str, pkg_name: &str, version: Option<&str>) {
  let rt = |s: &mut String, tuple: &str, indent: usize| {
    require_tuple(s, local_name, pkg_name, tuple, indent, version);
  };

  s.push_str(
    "  } else if (process.platform === 'android') {\n\
         \x20   if (process.arch === 'arm64') {\n",
  );
  rt(s, "android-arm64", 6);
  s.push_str("    } else if (process.arch === 'arm') {\n");
  rt(s, "android-arm-eabi", 6);
  s.push_str(
        "    } else {\n\
         \x20     loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))\n\
         \x20   }\n",
    );

  // win32
  s.push_str(
        "  } else if (process.platform === 'win32') {\n\
         \x20   if (process.arch === 'x64') {\n\
         \x20     if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {\n",
    );
  rt(s, "win32-x64-gnu", 8);
  s.push_str("      } else {\n");
  rt(s, "win32-x64-msvc", 8);
  s.push_str(
    "      }\n\
         \x20   } else if (process.arch === 'ia32') {\n",
  );
  rt(s, "win32-ia32-msvc", 6);
  s.push_str("    } else if (process.arch === 'arm64') {\n");
  rt(s, "win32-arm64-msvc", 6);
  s.push_str(
        "    } else {\n\
         \x20     loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))\n\
         \x20   }\n",
    );

  // darwin
  s.push_str("  } else if (process.platform === 'darwin') {\n");
  rt(s, "darwin-universal", 4);
  s.push_str("    if (process.arch === 'x64') {\n");
  rt(s, "darwin-x64", 6);
  s.push_str("    } else if (process.arch === 'arm64') {\n");
  rt(s, "darwin-arm64", 6);
  s.push_str(
        "    } else {\n\
         \x20     loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))\n\
         \x20   }\n",
    );

  // freebsd
  s.push_str(
    "  } else if (process.platform === 'freebsd') {\n\
         \x20   if (process.arch === 'x64') {\n",
  );
  rt(s, "freebsd-x64", 6);
  s.push_str("    } else if (process.arch === 'arm64') {\n");
  rt(s, "freebsd-arm64", 6);
  s.push_str(
        "    } else {\n\
         \x20     loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))\n\
         \x20   }\n",
    );

  // linux
  s.push_str(
    "  } else if (process.platform === 'linux') {\n\
         \x20   if (process.arch === 'x64') {\n\
         \x20     if (isMusl()) {\n",
  );
  rt(s, "linux-x64-musl", 8);
  s.push_str("      } else {\n");
  rt(s, "linux-x64-gnu", 8);
  s.push_str(
    "      }\n\
         \x20   } else if (process.arch === 'arm64') {\n\
         \x20     if (isMusl()) {\n",
  );
  rt(s, "linux-arm64-musl", 8);
  s.push_str("      } else {\n");
  rt(s, "linux-arm64-gnu", 8);
  s.push_str(
    "      }\n\
         \x20   } else if (process.arch === 'arm') {\n\
         \x20     if (isMusl()) {\n",
  );
  rt(s, "linux-arm-musleabihf", 8);
  s.push_str("      } else {\n");
  rt(s, "linux-arm-gnueabihf", 8);
  s.push_str(
    "      }\n\
         \x20   } else if (process.arch === 'loong64') {\n\
         \x20     if (isMusl()) {\n",
  );
  rt(s, "linux-loong64-musl", 8);
  s.push_str("      } else {\n");
  rt(s, "linux-loong64-gnu", 8);
  s.push_str(
    "      }\n\
         \x20   } else if (process.arch === 'riscv64') {\n\
         \x20     if (isMusl()) {\n",
  );
  rt(s, "linux-riscv64-musl", 8);
  s.push_str("      } else {\n");
  rt(s, "linux-riscv64-gnu", 8);
  s.push_str(
    "      }\n\
         \x20   } else if (process.arch === 'ppc64') {\n",
  );
  rt(s, "linux-ppc64-gnu", 6);
  s.push_str("    } else if (process.arch === 's390x') {\n");
  rt(s, "linux-s390x-gnu", 6);
  s.push_str(
        "    } else {\n\
         \x20     loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))\n\
         \x20   }\n",
    );

  // openharmony
  s.push_str(
    "  } else if (process.platform === 'openharmony') {\n\
         \x20   if (process.arch === 'arm64') {\n",
  );
  rt(s, "openharmony-arm64", 6);
  s.push_str("    } else if (process.arch === 'x64') {\n");
  rt(s, "openharmony-x64", 6);
  s.push_str("    } else if (process.arch === 'arm') {\n");
  rt(s, "openharmony-arm", 6);
  s.push_str(
        "    } else {\n\
         \x20     loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))\n\
         \x20   }\n",
    );

  // fallback
  s.push_str(
        "  } else {\n\
         \x20   loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))\n\
         \x20 }\n",
    );
}
