use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

use anyhow::Context;
use serde::Deserialize;

pub const DEFAULT_TYPE_DEF_HEADER: &str = "/* auto-generated by NAPI-RS */\n/* eslint-disable */\n";

const TOP_LEVEL_NAMESPACE: &str = "__TOP_LEVEL_MODULE__";

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TypeDefKind {
    Const,
    Enum,
    StringEnum,
    Interface,
    Type,
    Fn,
    Struct,
    NonConstructibleClass,
    Extends,
    Impl,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NativeParentLine {
    pub rust_path: Vec<String>,
    pub js_name: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct TypeDefLine {
    pub kind: TypeDefKind,
    pub name: String,
    pub original_name: Option<String>,
    pub def: String,
    pub extends: Option<String>,
    #[serde(default)]
    pub extends_kind: Option<TypeDefKind>,
    pub native_parent: Option<NativeParentLine>,
    pub js_doc: Option<String>,
    pub js_mod: Option<String>,
}

pub struct TypeDefOutput {
    pub dts: String,
    pub exports: Vec<String>,
}

pub fn process_type_def(
    intermediate_type_file: &Path,
    const_enum: bool,
    runtime_string_enum: bool,
) -> anyhow::Result<TypeDefOutput> {
    let content = std::fs::read_to_string(intermediate_type_file)
        .with_context(|| format!("Failed to read {}", intermediate_type_file.display()))?;

    let mut defs: Vec<TypeDefLine> = content
        .lines()
        .filter(|l| !l.is_empty())
        .map(|line| {
            let mut parsed: TypeDefLine =
                serde_json::from_str(line.trim()).context("Failed to parse type def line")?;
            if let Some(ref mut js_doc) = parsed.js_doc {
                *js_doc = js_doc.replace("\\n", "\n");
            }
            parsed.def = parsed.def.replace("\\n", "\n");
            Ok(parsed)
        })
        .collect::<anyhow::Result<_>>()?;

    defs.sort_by(|a, b| {
        let a_is_class = matches!(
            a.kind,
            TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
        );
        let b_is_class = matches!(
            b.kind,
            TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
        );
        match (a_is_class, b_is_class) {
            (true, true) | (false, false) => a.name.cmp(&b.name),
            (true, false) => std::cmp::Ordering::Less,
            (false, true) => std::cmp::Ordering::Greater,
        }
    });

    let grouped = preprocess_type_def(&mut defs)?;

    let mut exports = Vec::new();
    let mut dts = String::new();
    let mut first = true;

    let mut sorted_namespaces: Vec<_> = grouped.into_iter().collect();
    sorted_namespaces.sort_by(|(a, _), (b, _)| a.cmp(b));

    for (namespace, ns_defs) in sorted_namespaces {
        if !first {
            dts.push_str("\n\n");
        }
        first = false;

        if namespace == TOP_LEVEL_NAMESPACE {
            let mut ns_first = true;
            for def in &ns_defs {
                if !ns_first {
                    dts.push_str("\n\n");
                }
                ns_first = false;

                match def.kind {
                    TypeDefKind::Const
                    | TypeDefKind::Enum
                    | TypeDefKind::StringEnum
                    | TypeDefKind::Fn
                    | TypeDefKind::Struct
                    | TypeDefKind::NonConstructibleClass => {
                        exports.push(def.name.clone());
                    }
                    _ => {}
                }
                dts.push_str(&pretty_print(def, const_enum, runtime_string_enum, 0, false));
            }
        } else {
            exports.push(namespace.clone());
            write!(dts, "export declare namespace {namespace} {{\n").unwrap();
            for def in &ns_defs {
                dts.push_str(&pretty_print(def, const_enum, runtime_string_enum, 2, true));
                dts.push('\n');
            }
            dts.push('}');
        }
    }
    dts.push('\n');

    Ok(TypeDefOutput { dts, exports })
}

fn pretty_print(
    line: &TypeDefLine,
    const_enum: bool,
    runtime_string_enum: bool,
    indent: usize,
    ambient: bool,
) -> String {
    let mut s = line.js_doc.clone().unwrap_or_default();

    match line.kind {
        TypeDefKind::Interface => {
            write!(s, "export interface {} {{\n{}\n}}", line.name, line.def).unwrap();
        }
        TypeDefKind::Type => {
            write!(s, "export type {} = \n{}", line.name, line.def).unwrap();
        }
        TypeDefKind::Enum => {
            let kw = if const_enum { "const enum" } else { "enum" };
            write!(
                s,
                "{} {kw} {} {{\n{}\n}}",
                export_declare(ambient),
                line.name,
                line.def
            )
            .unwrap();
        }
        TypeDefKind::StringEnum => {
            if const_enum {
                write!(
                    s,
                    "{} const enum {} {{\n{}\n}}",
                    export_declare(ambient),
                    line.name,
                    line.def
                )
                .unwrap();
            } else if runtime_string_enum {
                write!(
                    s,
                    "{} enum {} {{\n{}\n}}",
                    export_declare(ambient),
                    line.name,
                    line.def
                )
                .unwrap();
            } else {
                let union_parts: String = line
                    .def
                    .lines()
                    .map(|l| {
                        // strip everything before '='
                        l.find('=')
                            .map(|i| l[i + 1..].trim_end_matches(',').trim())
                            .unwrap_or(l.trim())
                    })
                    .collect::<Vec<_>>()
                    .join(" | ");
                write!(s, "export type {} = {union_parts};", line.name).unwrap();
            }
        }
        TypeDefKind::Struct => {
            let mut def = line.def.clone();
            let mut extends_clause = String::new();
            let mut instance_extends = String::new();

            if let Some(ref ext) = line.extends {
                if let Some(next_sig) = iterator_next_signature(ext) {
                    write!(extends_clause, " extends {ext}").unwrap();
                    write!(def, "\n{next_sig}").unwrap();
                } else {
                    match line.extends_kind {
                        Some(TypeDefKind::Struct) => {
                            write!(extends_clause, " extends {ext}").unwrap();
                        }
                        Some(TypeDefKind::NonConstructibleClass) => {
                            write!(
                                instance_extends,
                                "{} interface {} extends {ext} {{}}",
                                export_declare(ambient),
                                line.name,
                            )
                            .unwrap();
                        }
                        _ => {}
                    }
                }
            }

            write!(
                s,
                "{} class {}{extends_clause} {{\n{def}\n}}",
                export_declare(ambient),
                line.name,
            )
            .unwrap();
            if !instance_extends.is_empty() {
                write!(s, "\n{instance_extends}").unwrap();
            }
            if let Some(ref orig) = line.original_name {
                if orig != &line.name {
                    write!(s, "\nexport type {orig} = {}", line.name).unwrap();
                }
            }
        }
        TypeDefKind::NonConstructibleClass => {
            let (instance_def, static_def) = split_non_constructible_class_def(&line.def);
            let extends_clause = line
                .extends
                .as_ref()
                .map(|e| format!(" extends {e}"))
                .unwrap_or_default();

            write!(
                s,
                "export interface {}{extends_clause} {{\n{instance_def}\n}}",
                line.name,
            )
            .unwrap();
            write!(
                s,
                "\n{} const {}: {{\n{static_def}",
                export_declare(ambient),
                line.name,
            )
            .unwrap();
            if !static_def.is_empty() {
                s.push('\n');
            }
            s.push_str("[Symbol.hasInstance](value: unknown): boolean\n}");

            if let Some(ref orig) = line.original_name {
                if orig != &line.name {
                    write!(s, "\nexport type {orig} = {}", line.name).unwrap();
                }
            }
        }
        TypeDefKind::Fn => {
            write!(s, "{} {}", export_declare(ambient), line.def).unwrap();
        }
        _ => {
            s.push_str(&line.def);
        }
    }

    correct_string_indent(&s, indent)
}

fn split_non_constructible_class_def(def: &str) -> (String, String) {
    let mut instance_lines = Vec::new();
    let mut static_lines = Vec::new();

    for line in def.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("constructor(") {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("static ") {
            static_lines.push(rest.to_string());
        } else {
            instance_lines.push(line.to_string());
        }
    }

    (instance_lines.join("\n"), static_lines.join("\n"))
}

fn iterator_next_signature(extends: &str) -> Option<String> {
    let inner = extends.strip_suffix('>')?.rsplit_once("Iterator<")?.1;
    let parts: Vec<&str> = inner.split(',').map(|p| p.trim()).collect();
    if parts.is_empty() {
        return None;
    }
    let t = parts[0];
    let t_result = parts.get(1).unwrap_or(&"undefined");
    let t_next = parts.get(2).unwrap_or(&"undefined");
    Some(format!(
        "next(value?: {t_next}): IteratorResult<{t}, {t_result}>"
    ))
}

fn export_declare(ambient: bool) -> &'static str {
    if ambient { "export" } else { "export declare" }
}

pub fn correct_string_indent(src: &str, indent: usize) -> String {
    let mut bracket_depth: usize = 0;
    let mut result = Vec::new();

    for line in src.split('\n') {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            result.push(String::new());
            continue;
        }

        let is_multiline_comment = trimmed.starts_with('*');
        let is_closing_bracket = trimmed.ends_with('}');
        let is_opening_bracket = trimmed.ends_with('{');
        let is_type_declaration = trimmed.ends_with('=');
        let is_type_variant = trimmed.starts_with('|');

        let right_indent;
        if (is_opening_bracket || is_type_declaration) && !is_multiline_comment {
            bracket_depth += 1;
            right_indent = indent + (bracket_depth - 1) * 2;
        } else {
            if is_closing_bracket
                && bracket_depth > 0
                && !is_multiline_comment
                && !is_type_variant
            {
                bracket_depth -= 1;
            }
            right_indent = indent + bracket_depth * 2;
        }

        let extra = if is_multiline_comment { 1 } else { 0 };
        let total_indent = right_indent + extra;
        result.push(format!("{}{trimmed}", " ".repeat(total_indent)));
    }

    result.join("\n")
}

type NamespaceGroups = BTreeMap<String, Vec<TypeDefLine>>;

fn preprocess_type_def(defs: &mut [TypeDefLine]) -> anyhow::Result<NamespaceGroups> {
    let mut namespace_grouped: BTreeMap<String, Vec<TypeDefLine>> = BTreeMap::new();
    // class_defs: (namespace\0name) -> Vec<index into defs>
    let mut class_defs: BTreeMap<String, Vec<usize>> = BTreeMap::new();

    let namespace_of = |def: &TypeDefLine| -> String {
        def.js_mod
            .clone()
            .unwrap_or_else(|| TOP_LEVEL_NAMESPACE.to_string())
    };

    let class_key = |ns: &str, name: &str| -> String { format!("{ns}\0{name}") };

    // First pass: register class defs
    for (i, def) in defs.iter().enumerate() {
        if matches!(
            def.kind,
            TypeDefKind::Struct | TypeDefKind::NonConstructibleClass
        ) {
            let ns = namespace_of(def);
            class_defs
                .entry(class_key(&ns, &def.name))
                .or_default()
                .push(i);
            if let Some(ref orig) = def.original_name {
                if orig != &def.name {
                    class_defs
                        .entry(class_key(&ns, orig))
                        .or_default()
                        .push(i);
                }
            }
        }
    }

    let find_class = |ns: &str, name: &str, requester: &str| -> anyhow::Result<Option<usize>> {
        let key = class_key(ns, name);
        match class_defs.get(&key) {
            None => Ok(None),
            Some(indices) if indices.len() == 1 => Ok(Some(indices[0])),
            Some(_) => anyhow::bail!(
                "Native class parent {name} for {requester} is ambiguous in the TypeScript generation unit"
            ),
        }
    };

    // Second pass: merge impl/extends into class defs, build namespace groups
    // We need to do this carefully since we mutate defs while iterating
    let len = defs.len();
    let mut skip = vec![false; len];

    for i in 0..len {
        let ns = namespace_of(&defs[i]);

        match defs[i].kind {
            TypeDefKind::Struct | TypeDefKind::NonConstructibleClass => {
                // resolve native_parent
                if defs[i].native_parent.is_some() {
                    let parent_name = {
                        let np = defs[i].native_parent.as_ref().unwrap();
                        np.js_name
                            .clone()
                            .or_else(|| np.rust_path.last().cloned())
                            .context(format!(
                                "Native class parent for {} has no Rust path",
                                defs[i].name
                            ))?
                    };
                    if let Some(pidx) = find_class(&ns, &parent_name, &defs[i].name)? {
                        let parent_name = defs[pidx].name.clone();
                        let parent_kind = defs[pidx].kind.clone();
                        defs[i].extends = Some(parent_name);
                        defs[i].extends_kind = Some(parent_kind);
                    } else {
                        anyhow::bail!(
                            "Native class parent {} for {} is not present in the same TypeScript generation unit",
                            parent_name,
                            defs[i].name,
                        );
                    }
                }
                // resolve extends (non-native)
                if let Some(ref ext) = defs[i].extends {
                    if iterator_next_signature(ext).is_none() {
                        let ext_name = ext.clone();
                        if let Some(pidx) = find_class(&ns, &ext_name, &defs[i].name)? {
                            let parent_name = defs[pidx].name.clone();
                            let parent_kind = defs[pidx].kind.clone();
                            defs[i].extends = Some(parent_name);
                            defs[i].extends_kind = Some(parent_kind);
                        }
                    }
                }
            }
            TypeDefKind::Extends => {
                skip[i] = true;
                let def_name = defs[i].name.clone();
                let def_def = defs[i].def.clone();
                if let Some(cidx) = find_class(&ns, &def_name, &def_name)? {
                    if defs[cidx].extends.is_some() {
                        if let Some(next_sig) = iterator_next_signature(&def_def) {
                            if !defs[cidx].def.is_empty() {
                                defs[cidx].def.push('\n');
                            }
                            defs[cidx].def.push_str(&next_sig);
                        }
                    } else {
                        defs[cidx].extends = Some(def_def);
                        // re-resolve extends
                        if let Some(ref ext) = defs[cidx].extends {
                            if iterator_next_signature(ext).is_none() {
                                let ext_name = ext.clone();
                                if let Some(pidx) =
                                    find_class(&ns, &ext_name, &defs[cidx].name)?
                                {
                                    let parent_name = defs[pidx].name.clone();
                                    let parent_kind = defs[pidx].kind.clone();
                                    defs[cidx].extends = Some(parent_name);
                                    defs[cidx].extends_kind = Some(parent_kind);
                                }
                            }
                        }
                    }
                }
            }
            TypeDefKind::Impl => {
                skip[i] = true;
                let def_name = defs[i].name.clone();
                let def_def = defs[i].def.clone();
                if let Some(cidx) = find_class(&ns, &def_name, &def_name)? {
                    if !defs[cidx].def.is_empty() {
                        defs[cidx].def.push('\n');
                    }
                    defs[cidx].def.push_str(&def_def);
                    if defs[cidx].kind == TypeDefKind::NonConstructibleClass
                        && has_constructor_signature(&def_def)
                    {
                        defs[cidx].kind = TypeDefKind::Struct;
                    }
                    defs[cidx].def = defs[cidx].def.replace("\\n", "\n");
                }
            }
            _ => {}
        }
    }

    // Post-pass: check structs without constructors → NonConstructibleClass
    for indices in class_defs.values() {
        for &idx in indices {
            if defs[idx].kind == TypeDefKind::Struct
                && !has_constructor_signature(&defs[idx].def)
            {
                defs[idx].kind = TypeDefKind::NonConstructibleClass;
            }
        }
    }

    // Build namespace groups (excluding merged entries)
    for (i, def) in defs.iter().enumerate() {
        if skip[i] {
            continue;
        }
        let ns = namespace_of(def);
        namespace_grouped
            .entry(ns)
            .or_default()
            .push(def.clone());
    }

    Ok(namespace_grouped)
}

fn has_constructor_signature(def: &str) -> bool {
    def.lines()
        .any(|l| l.trim().starts_with("constructor(") || l.trim().starts_with("constructor ("))
}
